---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-greeting-app-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-greeting-app
  template:
    metadata:
      labels:
        app: go-greeting-app
        version: v1
    spec:
      containers:
      - name: go-greeting-app
        image: jrreid/go-greeting-app:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081
