---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-greeting-app-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-greeting-app
  template:
    metadata:
      labels:
        app: go-greeting-app
        version: v1
        sealID: "345872"
        moduleID: "345872-1"
        costCenter: "01234"
    spec:
      containers:
      - name: go-greeting-app
        image: 218613010274.dkr.ecr.us-east-1.amazonaws.com/go-greeting-app:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081
